apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - namespace.yaml
  - https://github.com/metallb/metallb/config/manifests?ref=v0.14.9
  - config.yaml
