apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: op-connect-token
  namespace: onepassword
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgBxQxsV0YzivVhLxJdP0gb/mWX6IIrli4lK5fWFIQ+5TOLBAe4s1YgbZ7tj7Q9jNWXCcHzfk9P//mtPMx6cyU1P7o+KQ93NQhteZFjRAtle8Q6g7ByqAR2fvbfUAMvQwM+knCNifD9D8AcJoUv4Q4ItOe4F1oZtgDVc+uI7nx59b8I7Xpzpz2ABNJ0H0ciQ34paJ8L+lixgsyYx2AY0KFSeOKUAQiSWZNuQ+b3h6CqtjZzitQHFos0aU51TLgtGP471/vv7KXBfmhK3OVhVdLfSKt5sWY1YqDuv/RK8+j7XPRvJCgAVQB4cgqNdMlsxZwa9W/X1r+svQ88dmJFqt26sOVoQXufqf1VoVnI49vJ0nMPE/owaR8JWLjwA9ZhcDDRahwmjK77LatRjhNIX3zZFvZmASskPtWTFzrjUjLk93ABq/HLcPd7M5YuOTDAUgmyY85VwRXRAAfDtGwfpzPs+gD08wpqbQ1YWri/0nTCYiPV35KCOriHUQdFFPMutSIoSq140hAldVpxdeI7pjUT9RwPF03XcuuMCNruS264sTVv9wls7FG2CRu5PBXqLOxfy7S15k47Z71CYocBU+IvX/Nz7xot2zp69SgqSsD9WyVQX9OBczzFHTQP8FN0l9qoz8R17lhZqEBFas6zvrI/mBhFrhxf0AZ36q4tuc+7LxDw4awMAalJwvkQgVBWI8uoXqvqKWSlkhHhbJQR56eQGJECUrdpt9j+t6+QorEWGRG1DrfC09ih07KGCuruQPSi/yH3KJ52iNOATFESojCnRbDnB8OPDGsIsHzeZpbEGd4Hu+KGbn5k+T4LhNaKrwKsPgCkohB2/PpK+aKjxZyni4QV/Vdo7dOlASCPHllDW9QwFxVB6JnELH1jzeE4Cr8GCzwtjrvgIUGipmGWPHwCA7Dluty9T41VwBXwu1CjVm3zcT4YjxjT9fUUapOrmnB9VSk6WC2svsWy/pjDOb/71dNDHgmfvFFWlxpZMLp3ESM/mAeTXaaXFmSgJEhTbG8UDR9lSEYdzng4gTXvi0xEEAau/eQFAaIDeRnuHTmGDLpS9XpkRKNU+m2xozdcvbgP6o/2neMUPFP+oDNzNy/SSIo5P1bLRdcJSe5PsDvM1Sszlz0oE9Kt/fC3QoexXSuA5D50A9Fzh7WNTuq1z9dXSZeuvMQdirxNSy0btmKSrY95I5ZiYqc9TZ1L7Bi8tvyX1PZBmNSLXFD70zjrZ73EbRA1DyhN3+yJWKcVDxL6RCLd7EDM6l4KD9KCVi6I5jFxL4MT9bDSdevZC2qAO7yJdIWzj4HEnEJkSKZ5Wi7CJ7PRtC56LJ++c585p7e22ERnOvHwBV9o7Y2lV0XyJ2F0xEw5TxdAjFCd/deUvpGozNdWBdmMKsjLAj4WCpWS3d+SehF2a89xiWhgr7Q7qocU+fUaWN04mws0U+eavdHEk4NyauSe8xdeT0OZ71a+szoGUCrOfDpV+imd6HSiJ/k4trIw2LIzio7+cvtaC1NnZ7sBgpnRRSkLBeTmIU/2o1LGOpbOaWZ5tYaFGmSRPPtyZZXQ=
  template:
    metadata:
      name: op-connect-token
      namespace: onepassword
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
