connect:
  credentialsName: op-connect-credentials
  credentialsKey: 1password-credentials.json
  serviceType: ClusterIP
  replicas: 1
  sync:
    httpPort: 8081
  api:
    httpPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

operator:
  create: false

token:
  name: op-connect-token
  key: token
