apiVersion: v1
kind: Secret
metadata:
  name: homepage-auth
  namespace: default
data:
  users: bnZlcmsxOTk3OiRhcHIxJGxLcmt6ejNIJEZGOW9zUUswNFBtekJTclUuQXhoNDAK
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homepage-auth
  namespace: default
spec:
  basicAuth:
    secret: homepage-auth
