apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: ["sh", "-c", "cp /tmp/config/* /app/config/"]
          volumeMounts:
            - name: config-source
              mountPath: /tmp/config
            - name: config-writable
              mountPath: /app/config

      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.nverk.me"
            - name: HOMEPAGE_VAR_JELLYFIN_KEY
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: jellyfin_key
            - name: HOMEPAGE_VAR_RADARR_KEY
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: radarr_key
            - name: HOMEPAGE_VAR_SONARR_KEY
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: sonarr_key
            - name: HOMEPAGE_VAR_PROWLARR_KEY
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: prowlarr_key
            - name: HOMEPAGE_VAR_QBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: qbit_password
            - name: HOMEPAGE_VAR_JELLYSEERR_KEY
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: jellyseerr_key
            - name: HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: cloudflare_account_id
            - name: HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: cloudflare_tunnel_id
            - name: HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: cloudflare_tunnel_token

          volumeMounts:
            - name: config-writable
              mountPath: /app/config

      volumes:
        - name: config-source
          configMap:
            name: homepage-config
        - name: config-writable
          emptyDir: {}
