apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
    - secretKey: jellyfin_key
      remoteRef:
        key: jellyfin
        property: credential
    - secretKey: radarr_key
      remoteRef:
        key: radarr
        property: credential
    - secretKey: sonarr_key
      remoteRef:
        key: sonarr
        property: credential
    - secretKey: prowlarr_key
      remoteRef:
        key: prowlarr
        property: credential
    - secretKey: qbit_password
      remoteRef:
        key: qbittorrent
        property: credential
