apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-config
    behavior: merge
    files:
      - configs/settings.yaml
      - configs/services.yaml
      - configs/widgets.yaml
      - configs/bookmarks.yaml
      - configs/kubernetes.yaml
      - configs/docker.yaml
      - configs/custom.css
      - configs/custom.js
