apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-account.yaml
  - secret.yaml
  - roles.yaml
  - auth.yaml
  - middleware.yaml
  - jobs/restart.yaml
