apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: op-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword.svc:8080
      vaults:
        Homelab: 0
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-connect-token
            namespace: onepassword
            key: token
