apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../flaresolverr
  - ../radarr
  - ../sonarr
  - ../readarr
  - ../prowlarr
  - ../qbittorrent
  - ../jellyfin
  - ../jellyseerr
  - ../kavita
  - ../filebrowser
