apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kavita-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: books.nverk.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kavita-service
                port:
                  number: 5000
