apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbit-ingress
  namespace: default
spec:
  rules:
    - host: torrent.192.168.1.30.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbit-service
                port:
                  name: web-ui
  tls:
    - hosts:
        - torrent.192.168.1.30.sslip.io
