apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: default
data:
  config.yaml: |
    ingress:
      - hostname: "*.nverk.me"
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
