apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-tunnel
        property: credential
