apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik-generator
name: traefik
repo: https://traefik.github.io/charts
version: 38.0.1
releaseName: traefik
namespace: traefik
valuesFile: values.yaml
