apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-api
  namespace: onepassword
  labels:
    app: onepassword-connect-api
    app.kubernetes.io/name: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect-api
  template:
    metadata:
      labels:
        app: onepassword-connect-api
        app.kubernetes.io/name: onepassword-connect
    spec:
      containers:
        - name: connect-api
          image: 1password/connect-api:1.7.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: onepassword-connect-bus.onepassword.svc.cluster.local:11220
          volumeMounts:
            - name: op-credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
            - name: op-data
              mountPath: /home/opuser/.op/data
      volumes:
        - name: op-credentials
          secret:
            secretName: op-connect-credentials
        - name: op-data
          emptyDir: {}
