apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: onepassword
  labels:
    app: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
    spec:
      containers:
        - name: connect-api
          image: 1password/connect-api:1.7.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
          volumeMounts:
            - name: op-credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
            - name: op-data
              mountPath: /home/opuser/.op/data
        - name: connect-sync
          image: 1password/connect-sync:1.7.3
          imagePullPolicy: IfNotPresent
          env:
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
          volumeMounts:
            - name: op-credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
            - name: op-data
              mountPath: /home/opuser/.op/data
      volumes:
        - name: op-credentials
          secret:
            secretName: op-connect-credentials
        - name: op-data
          emptyDir: {}
