apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-sync
  namespace: onepassword
  labels:
    app: onepassword-connect-sync
    app.kubernetes.io/name: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect-sync
  template:
    metadata:
      labels:
        app: onepassword-connect-sync
        app.kubernetes.io/name: onepassword-connect
    spec:
      containers:
        - name: connect-sync
          image: 1password/connect-sync:1.7.3
          imagePullPolicy: IfNotPresent
          env:
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: onepassword-connect-api-bus.onepassword.svc.cluster.local:11220
          volumeMounts:
            - name: op-credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
            - name: op-data
              mountPath: /home/opuser/.op/data
      volumes:
        - name: op-credentials
          secret:
            secretName: op-connect-credentials
        - name: op-data
          emptyDir: {}
