apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onepassword

resources:
  - namespace.yaml
  - sealedsecret-credentials.yaml
  - sealedsecret-token.yaml
helmCharts:
  - name: connect
    releaseName: onepassword-connect
    repo: https://1password.github.io/connect-helm-charts
    version: 2.1.1
    namespace: onepassword
    valuesFile: values.yaml
