apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onepassword

resources:
  - namespace.yaml
  - sealedsecret-credentials.yaml
  - sealedsecret-token.yaml
  - service.yaml
  - deployment-api.yaml
