apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  selector:
    app: onepassword-connect
  ports:
    - name: http
      port: 8080
      targetPort: 8080
