apiVersion: v1
kind: Service
metadata:
  name: qbit-service
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - name: web-ui
      port: 8080
      targetPort: webui
    - name: bittorrent-tcp
      port: 6881
      targetPort: bittorrent
      protocol: TCP
    - name: bittorrent-udp
      port: 6881
      targetPort: bittorrent-udp
      protocol: UDP
  type: LoadBalancer
