apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-pvc-lp
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-wffc
  resources:
    requests:
      storage: 1Gi
